### What is Tensor ?

###### A tensor id ofter thought of as a generalized matrix
###### We can have 1D, 2D, 3D, ND tensors

<br>vector = 1D Tensor<br>
<br>Matrix = 2D Tensor<br>
<br>Tensor >= 3D<br>

In [100]:
import torch
import numpy as np

## <u> Tensor Basics

<strong><tt>torch.Tensor</tt></strong></a> is a multi-dimensional matrix containing elements of a single data type.<br>
Calculations between tensors can only happen if the tensors share the <u> same dtype.<br>

In [101]:
#creating numpy array to Companre
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


##### 1. Creating the 1-D Tensor

In [102]:
#INITIALIZING TENSOR
x=torch.from_numpy(arr)

#GloBAL = torch.as_tensor(arr)
print(x)

"""Carefully look at the DATA type"""

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


'Carefully look at the DATA type'

In [103]:
#Using the "as_tensor Command"

a=[1,2,3,4]
y=torch.as_tensor(a)
print(y)
print("Data Type = ",y.dtype)
print("Type = ",y.type())

tensor([1, 2, 3, 4])
Data Type =  torch.int64
Type =  torch.LongTensor


##### 2. Creating the 2-D Tensor

In [104]:
# EXAMPLE 2 - MATRIX
arr= np.arange(0,12).reshape(4,3)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [105]:
#creating tensor from MATRIX
tensor_mat = torch.as_tensor(arr)
print(tensor_mat)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], dtype=torch.int32)


In [106]:
# EXAMPLE 3 - MATRIX
arr= np.arange(0.0,12.0).reshape(4,3)
print(arr)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [107]:
#creating tensor from MATRIX
tensor_mat = torch.as_tensor(arr)
print(tensor_mat)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)


In [108]:
""" Notice the Change in Dtype """
""" Here "torch.DoubleTensor" refers to 64-bit floating point data."""

' Here "torch.DoubleTensor" refers to 64-bit floating point data.'

<a> Changing the dtype of existing tensors

In [109]:
x = torch.tensor([8,9,-3], dtype=torch.int)
print(x)
print(x.dtype)
print(x.type())

tensor([ 8,  9, -3], dtype=torch.int32)
torch.int32
torch.IntTensor


In [110]:
# Change its type to torch.int64

print("Old type: ",x.type())

x=x.type(torch.int64)

print("New type: ", x.type())

Old type:  torch.IntTensor
New type:  torch.LongTensor


<h4><a>Tensor Datatypes</a></h4>
<table style="display: inline-block">
<tr><th>TYPE</th><th>NAME</th><th>EQUIVALENT</th><th>TENSOR TYPE</th></tr>
<tr><td>32-bit integer (signed)</td><td>torch.int32</td><td>torch.int</td><td>IntTensor</td></tr>
<tr><td>64-bit integer (signed)</td><td>torch.int64</td><td>torch.long</td><td>LongTensor</td></tr>
<tr><td>16-bit integer (signed)</td><td>torch.int16</td><td>torch.short</td><td>ShortTensor</td></tr>
<tr><td>32-bit floating point</td><td>torch.float32</td><td>torch.float</td><td>FloatTensor</td></tr>
<tr><td>64-bit floating point</td><td>torch.float64</td><td>torch.double</td><td>DoubleTensor</td></tr>
<tr><td>16-bit floating point</td><td>torch.float16</td><td>torch.half</td><td>HalfTensor</td></tr>
<tr><td>8-bit integer (signed)</td><td>torch.int8</td><td></td><td>CharTensor</td></tr>
<tr><td>8-bit integer (unsigned)</td><td>torch.uint8</td><td></td><td>ByteTensor</td></tr></table>

## <h4> Copying vs. sharing <h4>

<a><strong><tt>torch.from_numpy()</tt></strong></a><br>
<a><strong><tt>torch.as_tensor()</tt></strong></a><br>
<a><strong><tt>torch.tensor()</tt></strong></a><br>

There are a number of different functions available for <a>creating tensors</a>. 
<br> When using <a><strong><tt>torch.from_numpy()</tt></strong></a> and <a><strong><tt>torch.as_tensor()</tt></strong></a>, the PyTorch tensor and the source NumPy array share the same memory. </br>

This means that changes to one affect the other. However, the <a><strong><tt>torch.tensor()</tt></strong></a> function always makes a copy.

In [111]:
#using torch.from_numpy

ar= np.arange(0,5)
t=torch.from_numpy(ar)
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [112]:
# proof that they share same memory
print("orginial ar = ",ar)
print("original tensor = ",t)
ar[2]=7
t[1]=-1
print("ar after change in ar = ",ar)
print("tensor after change in t = ",t)

orginial ar =  [0 1 2 3 4]
original tensor =  tensor([0, 1, 2, 3, 4], dtype=torch.int32)
ar after change in ar =  [ 0 -1  7  3  4]
tensor after change in t =  tensor([ 0, -1,  7,  3,  4], dtype=torch.int32)


<h4> Class constructors </h4>
<a><strong><tt>torch.Tensor()</tt></strong></a><br>
<a><strong><tt>torch.FloatTensor()</tt></strong></a><br>
<a><strong><tt>torch.LongTensor()</tt></strong></a>, etc.<br>

There's a subtle difference between using the factory function <font color=red><tt>torch.tensor(data)</tt></font> and the class constructor <font color=red><tt>torch.Tensor(data)</tt></font>.<br>
The factory function determines the dtype from the incoming data, or from a passed-in dtype argument.<br>
The class constructor <tt>torch.Tensor()</tt>is simply an alias for <tt>torch.FloatTensor(data)</tt>. Consider the following:

In [113]:
data = np.array([1,2,3])

In [114]:
# Equivalent to cc = torch.FloatTensor(data)

# It torch.Tensor() converts the data to FloatTensor (necessarily)
a= torch.Tensor(data)
print(a, a.type())

tensor([1., 2., 3.]) torch.FloatTensor


In [115]:
# using torch.tensor()

b = torch.tensor(data)
print(b, b.type())

#this does not explicitly change the data type

tensor([1, 2, 3], dtype=torch.int32) torch.IntTensor


In [116]:
# using explicit conversion to torch.long

c = torch.tensor(data, dtype=torch.long)
print(c, c.type())

tensor([1, 2, 3]) torch.LongTensor


<h4> <a> Creating tensors from scratch </h4>

1. Uninitialized tensors with <tt>.empty()</tt>

<a><strong><tt>torch.empty()</tt></strong></a> returns an <em>uninitialized</em> tensor.

In [117]:
# Essentially a block of memory is allocated according 
# to the size of the tensor.
# This is similar to the behavior of <tt>numpy.empty()</tt>.

In [118]:
x = torch.empty(4, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


2. Initialized tensors with <tt>.zeros()</tt> and <tt>.ones()</tt>
###### It's a good idea to pass in the intended dtype.

In [119]:
#Creating a Zero Tensor of 4x3 size
x= torch.zeros(4,3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [120]:
#Creating a One Tensor of 4x3 size
x= torch.ones(4,3, dtype=torch.int64)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


<h4> <a>Tensors from ranges

<a><strong><tt>torch.arange(start,end,step)</tt></strong></a><br>
<a><strong><tt>torch.linspace(start,end,steps)</tt></strong></a><br>
Note that with <tt>.arange()</tt>, <tt>end</tt> is exclusive, while with <tt>linspace()</tt>, <tt>end</tt> is inclusive.

<br> Same as numpy

In [121]:
#Using arange
x=torch.arange(0,18,2)
print(x)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])


In [122]:
#using linspace
x=torch.linspace(0,18,12).reshape(4,3)
print(x)

tensor([[ 0.0000,  1.6364,  3.2727],
        [ 4.9091,  6.5455,  8.1818],
        [ 9.8182, 11.4545, 13.0909],
        [14.7273, 16.3636, 18.0000]])


<h4><a>Random number tensors


<a><strong><tt>torch.rand(size)</tt></strong></a> returns random samples from a uniform dist over [0, 1)<br>
<a><strong><tt>torch.randn(size)</tt></strong></a> returns samples from the "standard normal" dist [σ = 1]<br>
Unlike <tt>rand</tt> which is uniform, values closer to zero are more likely to appear.<br>
<a><strong><tt>torch.randint(low,high,size)</tt></strong></a> returns random integers from low (inclusive) to high (exclusive)<br>
Same as Numpy

In [123]:
# random samples from a uniform dist over [0, 1)
x = torch.rand(4, 3)
print(x)

tensor([[0.1311, 0.1731, 0.8367],
        [0.0046, 0.0186, 0.8609],
        [0.3978, 0.6337, 0.1008],
        [0.1572, 0.3382, 0.1770]])


In [124]:
# returns samples from the "standard normal" dist [σ = 1]
x = torch.randn(4, 3)
print(x)

tensor([[ 1.5506,  0.0601, -0.0161],
        [ 0.0352, -1.0895,  1.6982],
        [-1.8522, -0.5731,  0.4563],
        [-0.6152,  1.0014, -1.4056]])


In [125]:
#Different 
# Generate random no in range
x = torch.randint(0, 5, (4, 3))
print(x)

tensor([[1, 3, 1],
        [3, 4, 4],
        [4, 3, 2],
        [0, 0, 1]])


### Random number tensors that follow the input size
<a><strong><tt>torch.rand_like(input)</tt></strong></a><br>
<a><strong><tt>torch.randn_like(input)</tt></strong></a><br>
<a><strong><tt>torch.randint_like(input,low,high)</tt></strong></a><br> these return random number tensors with the same size as <tt>input</tt>

In [126]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [127]:
x2 = torch.randn_like(x)
print(x2)

tensor([[-0.6246, -0.5785, -0.3368,  0.1028,  0.8726],
        [-1.1405, -0.0407, -0.0814,  0.8923,  0.3031]])


The same syntax can be used with<br>
<a><strong><tt>torch.zeros_like(input)</tt></strong></a><br>
<a><strong><tt>torch.ones_like(input)</tt></strong></a>

In [128]:
x3 = torch.ones_like(x2)
print(x3)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


#############################################################

## <u> Tensor operations

<a>1. INDEXING and SLICING </a>

same as Numpy arrays

In [129]:
#generate 6 Values in 3x2 Matrix
x= torch.arange(6).reshape(2,3)
print("6 values =\n",x)

6 values =
 tensor([[0, 1, 2],
        [3, 4, 5]])


In [130]:
# All rows, of column index=1
x[:,1]

tensor([1, 4])

In [131]:
# All rows and columns =0,1
x[:,:2]

tensor([[0, 1],
        [3, 4]])

<a> 2. Reshape tensors with <tt>.view()</tt> </a>

In [132]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [133]:
# torch.View usage
x=x.view(2,5)
print(x)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


HIGHLIGHT -Difference

<h6> Although both <a> torch.view </a> and <a> torch.reshape </a> are used to reshape tensors, here are the differences between them.

<u>torch.view</u><br>
As the name suggests, torch.view merely creates a view of the original tensor. The new tensor will always share its data with the original tensor. This means that if you change the original tensor, the reshaped tensor will change and vice versa.<br>

To ensure that the new tensor always shares its data with the original, torch.view imposes some contiguity constraints on the shapes of the two tensors
<h6>


In [134]:
z = torch.zeros(3, 2)
x = z.view(2, 3)
z.fill_(1)
print(x)
# we can see that x also changed

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [135]:
#place where view wont' work.
z = torch.zeros(3, 2)
y = z.t()
y.size()
torch.Size([2, 3])
y.view(6)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

<h6> <u>torch.reshape </u> doesn't impose any contiguity constraints, but also doesn't guarantee data sharing.<br>

The new tensor may be a view of the original tensor, or it may be a new tensor altogether.

In [136]:
x = torch.zeros(3, 2)
print("org X= \n",x)
y = x.reshape(6)
print("\norg y= \n",y)
z = x.t().reshape(6)
print("\norg z= \n",z)

x.fill_(1)

print("\nModified x= \n",x)
print("\nModified y= \n",y)
print("\nModified z= \n",z)


org X= 
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

org y= 
 tensor([0., 0., 0., 0., 0., 0.])

org z= 
 tensor([0., 0., 0., 0., 0., 0.])

Modified x= 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

Modified y= 
 tensor([1., 1., 1., 1., 1., 1.])

Modified z= 
 tensor([0., 0., 0., 0., 0., 0.])


<a> Views can infer the correct size </a><br>
By passing in <tt>-1</tt> PyTorch will infer the correct value from the given tensor

<h6>Suppose we want an 2xN dim tensor so that N will be taken care of by the view

In [137]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [138]:
#now you want a 2d vector but dont know how many columns will it fi into
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [139]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

#############################################################

## <u> Tensor Arithmetic

In [140]:
a=torch.tensor([1,2,3], dtype=torch.float)
b=torch.tensor([4,5,6], dtype=torch.float)

<h6> <a> 3 ways to ADD

In [141]:
print(a+b)

tensor([5., 7., 9.])


In [142]:
torch.add(a,b)

tensor([5., 7., 9.])

In [143]:
a.add_(b) #equivalent to a=torch.add(a,b)

tensor([5., 7., 9.])

<a>Any operation that changes a tensor in-place is post-fixed with an underscore _.
    <br>In the above example: a.add__(b) changed <tt>a</tt>.

In [144]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(torch.add(a,b).sum())

tensor(21.)


<a><h4>Dot products

Dot products can be expressed as <a><strong><tt>torch.dot(a,b)</tt></strong></a> or `a.dot(b)` or `b.dot(a)`

In [145]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a.mul(b)) # for reference
print()
print(a.dot(b))

tensor([ 4., 10., 18.])

tensor(32.)


<a><h4> Matrix Multiplication

Matrix multiplication computed using <a><strong><tt>torch.mm(a,b)</tt></strong></a> or `a.mm(b)` or `a @ b`

In [146]:
a = torch.tensor([[0,2,4],[1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)

print('a: ',a.size())
print('b: ',b.size())
print('a x b: ',torch.mm(a,b).size())
print(torch.mm(a,b))

a:  torch.Size([2, 3])
b:  torch.Size([3, 2])
a x b:  torch.Size([2, 2])
tensor([[56., 62.],
        [80., 89.]])


In [147]:
t1 = torch.randn(2, 3, 4)
t2 = torch.randn(4, 5)

print(torch.matmul(t1, t2).size())

torch.Size([2, 3, 5])


However, the same operation raises a <tt><strong>RuntimeError</strong></tt> with <tt>torch.mm()</tt>:

In [148]:
print(torch.mm(t1, t2).size())

RuntimeError: self must be a matrix